# Generated by Django 4.2.16 on 2025-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
