# Generated by Django 4.2.16 on 2025-03-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
