# Generated by Django 4.2.16 on 2025-03-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_ip_adress_postview_ip_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headding',
            new_name='Heading',
        ),
    ]
